services:
    admin.admin.currency:
        class: AdminBundle\Admin\CurrencyAdmin
        arguments: [~, AppBundle\Entity\Currency, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Финансы, label: Валюты, show_mosaic_button: false }

    admin.admin.payment:
        class: AdminBundle\Admin\PaymentAdmin
        arguments: [~, AppBundle\Entity\Payment, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Финансы, label: Информация о платежах, show_mosaic_button: false }

    admin.admin.news:
        class: AdminBundle\Admin\NewsAdmin
        arguments: [~, AppBundle\Entity\News, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Информация, label: Новости, show_mosaic_button: false }

    admin.admin.static_page:
        class: AdminBundle\Admin\StaticPageAdmin
        arguments: [~, AppBundle\Entity\StaticPage, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Информация, label: Страницы с инф., show_mosaic_button: false }

    admin.admin.user:
        class: AdminBundle\Admin\UserAdmin
        arguments: [~, AppBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Пользователи, label: Список пользователей, show_mosaic_button: false }

    admin.admin.role:
        class: AdminBundle\Admin\RoleAdmin
        arguments: [~, AppBundle\Entity\Role, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Пользователи, label: Парва доступа, show_mosaic_button: false }

    admin.admin.bot_live_drop:
        class: AdminBundle\Admin\BotLiveDropAdmin
        arguments: [~, AppBundle\Entity\BotLiveDrop, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Кейсы, label: Bot live drop, show_mosaic_button: false }

    admin.admin.cases_csgo:
        class: AdminBundle\Admin\CasesCSGOAdmin
        arguments: [~, AppBundle\Entity\Cases, AdminBundle:CasesCSGOCRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Кейсы, label: Кейсы CSGO, show_mosaic_button: false }
        calls:
            - [ setTemplate, [edit, admin/cases_edit.html.twig]]
        public: true

    admin.admin.cases_pubg:
        class: AdminBundle\Admin\CasesPUBGAdmin
        arguments: [~, AppBundle\Entity\Cases, AdminBundle:CasesPUBGCRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Кейсы, label: Кейсы PUBG, show_mosaic_button: false }
        calls:
            - [ setTemplate, [edit, admin/cases_edit.html.twig]]
        public: true

    admin.admin.cases_category:
        class: AdminBundle\Admin\CasesCategoryAdmin
        arguments: [~, AppBundle\Entity\CasesCategory, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Кейсы, label: Категории, show_mosaic_button: false }

    admin.admin.cases_domain:
        class: AdminBundle\Admin\CasesDomainAdmin
        arguments: [~, AppBundle\Entity\CasesDomain, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Кейсы, label: Домены, show_mosaic_button: false }

    admin.admin.cases_static_page:
        class: AdminBundle\Admin\CasesStaticPageAdmin
        arguments: [~, AppBundle\Entity\CasesStaticPage, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Кейсы, label: Пол. информация, show_mosaic_button: false }

    admin.admin.statistic:
        class: AdminBundle\Admin\StatisticCasesAdmin
        arguments: [~, AppBundle\Entity\StatisticCases, AdminBundle:StatisticCasesCRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Кейсы, label: Cтатистика, show_mosaic_button: false }

    admin.admin.rarity_pubg:
        class: AdminBundle\Admin\RarityPUBGAdmin
        arguments: [~, AppBundle\Entity\RarityPUBG, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Скины PUBG, label: Раритетность, show_mosaic_button: false }

    admin.admin.skins_pubg:
        class: AdminBundle\Admin\SkinsPUBGAdmin
        arguments: [~, AppBundle\Entity\SkinsPUBG, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Скины PUBG, label: Скины, show_mosaic_button: false }

    admin.admin.rarity_csgo:
        class: AdminBundle\Admin\RarityAdmin
        arguments: [~, AppBundle\Entity\Rarity, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Скины CSGO, label: Древность, show_mosaic_button: false }

    admin.admin.quality_csgo:
        class: AdminBundle\Admin\QualityAdmin
        arguments: [~, AppBundle\Entity\Quality, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Скины CSGO, label: Качество, show_mosaic_button: false }

    admin.admin.weapon_csgo:
        class: AdminBundle\Admin\WeaponAdmin
        arguments: [~, AppBundle\Entity\Weapon, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Скины CSGO, label: Оружие, show_mosaic_button: false }

    admin.admin.item_set_csgo:
        class: AdminBundle\Admin\ItemSetAdmin
        arguments: [~, AppBundle\Entity\ItemSet, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Скины CSGO, label: Набор, show_mosaic_button: false }

    admin.admin.type_skins_csgo:
        class: AdminBundle\Admin\TypeSkinsAdmin
        arguments: [~, AppBundle\Entity\TypeSkins, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Скины CSGO, label: Тип, show_mosaic_button: false }

    admin.admin.decor_csgo:
        class: AdminBundle\Admin\DecorAdmin
        arguments: [~, AppBundle\Entity\Decor, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Скины CSGO, label: Оформление, show_mosaic_button: false }

    admin.admin.skins_csgo:
        class: AdminBundle\Admin\SkinsAdmin
        arguments: [~, AppBundle\Entity\Skins, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Скины CSGO, label: Основа для скинов, show_mosaic_button: false }

    admin.admin.skins_price_csgo:
        class: AdminBundle\Admin\SkinsPriceAdmin
        arguments: [~, AppBundle\Entity\SkinsPrice, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Скины CSGO, label: Скины на продаже, show_mosaic_button: false }

    admin.service.cases_list:
        class: AdminBundle\Service\CasesListService
        arguments: ['@doctrine.orm.default_entity_manager', "@logger"]

    admin.service.cases_list_pubg:
        class: AdminBundle\Service\CasesListPUBGService
        arguments: ['@doctrine.orm.default_entity_manager', "@logger"]
