<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BotLiveDropRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class BotLiveDropRepository extends EntityRepository
{
    /**
     * @param $hourCurrent
     * @return array
     * @throws \Doctrine\DBAL\DBALException
     */
    public function findBotUser($hourCurrent)
    {
        $dbal = $this->getEntityManager()->getConnection();
        $stmt = $dbal->prepare("
        SELECT bld.*, u.username FROM bot_live_drop bld 
          LEFT JOIN users u ON bld.user_id = u.id 
        WHERE bld.hour_from <= :hour_current AND bld.hour_to >= :hour_current
        ");
        $stmt->bindParam('hour_current', $hourCurrent, \PDO::PARAM_INT);
        $stmt->execute();

        return $stmt->fetchAll(\PDO::FETCH_ASSOC);
    }
}
