<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CasesSkinsPRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class CasesSkinsPUBGRepository extends EntityRepository
{
    /**
     * @param $casesId
     * @return array
     * @throws \Doctrine\DBAL\DBALException
     */
    public function findCasesSkinsByCasesId($casesId)
    {
        $dbal = $this->getEntityManager()->getConnection();
        $stmt = $dbal->prepare('
        SELECT
          cspubg.id,
          cspubg.skins_id,
          cspubg.procent_rarity,
          cspubg.is_drop as procent_skins,
          spubg.name,
          spubg.image as icon_url,
          spubg.rarity_id,
          spubg.steam_price
        FROM cases_skins_pubg cspubg
          LEFT JOIN skins_pubg spubg ON spubg.id = cspubg.skins_id
        WHERE
          cspubg.cases_id = :cases_id;
        ');
        $stmt->bindParam('cases_id', $casesId, \PDO::PARAM_INT);
        $stmt->execute();

        return $stmt->fetchAll(\PDO::FETCH_ASSOC);
    }
}
