<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RarityRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class RarityRepository extends EntityRepository
{
    /**
     * @param $casesId
     * @return array
     * @throws \Doctrine\DBAL\DBALException
     */
    public function findRarityByCasesId($casesId)
    {
        $dbal = $this->getEntityManager()->getConnection();
        $stmt = $dbal->prepare("
        SELECT r.id, r.localized_tag_name, cs.procent_rarity FROM rarity r
          LEFT JOIN skins s ON s.rarity_id = r.id
          LEFT JOIN cases_skins cs ON cs.skins_id = s.id
        WHERE
          cs.cases_id = :cases_id;
        ");
        $stmt->bindParam('cases_id', $casesId, \PDO::PARAM_INT);
        $stmt->execute();

        return $stmt->fetchAll();
    }
}
