<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SkinsPUBGRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class SkinsPUBGRepository extends EntityRepository
{
}
