services:
    processing.metrics.persister:
        class: ProcessingBundle\Metrics\Persister
        arguments: ["@doctrine.dbal.default_connection", "@logger"]

    processing.parser.skins_handler:
        class: ProcessingBundle\Parser\SkinsHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@doctrine.dbal.default_connection'

    processing.parser.price_handler:
        class: ProcessingBundle\Parser\PriceHandler
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@doctrine.dbal.default_connection"
            - "@logger"

    processing.parser.skins_image_handler:
        class: ProcessingBundle\Parser\SkinsImageHandler
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@doctrine.dbal.default_connection"
            - "@app.service.upload_image"
            - "%steam_community_image_url%"
