services:
    processing.parser.skins_handler:
        class: ProcessingBundle\Parser\SkinsHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@doctrine.dbal.default_connection'
            - '@guzzle.client.steam'
            - '@app.service.upload_image'
            - '@logger'
            - '%steam.steam_community_url%'

    processing.service.parser_market_handler:
        class: ProcessingBundle\Services\ParserMarketHandler
        arguments:
            - '@app.repository.skins'
            - '@steam.api_market'
            - '@logger'

    processing.metrics.persister:
        class: ProcessingBundle\Metrics\Persister
        arguments: ["@doctrine.dbal.default_connection", "@logger"]

    processing.parser.price_handler:
        class: ProcessingBundle\Parser\PriceHandler
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@doctrine.dbal.default_connection"
            - "@logger"
