imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: include/framework.yml }
    - { resource: include/doctrine.yml }
    - { resource: include/rabbitmq.yml }
    - { resource: include/redis.yml }
    - { resource: include/jmsserializer.yml }
    - { resource: include/fosrest.yml }
    - { resource: include/pagination.yml }
    - { resource: include/steam.yml }
    - { resource: include/sonata.yml }
    - { resource: include/swiftmailer.yml }
    - { resource: include/lexik_jwt_authentication.yml }
    - { resource: "@AdminBundle/Resources/config/services.yml" }
    - { resource: "@ApiBundle/Resources/config/services.yml" }
    - { resource: "@ApiCasesBundle/Resources/config/services.yml" }
    - { resource: "@ProcessingBundle/Resources/config/services.yml" }
