app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

api_cases_pubg:
    resource: "@ApiCasesPUBGBundle/Controller/"
    type:     annotation
    prefix:   /api/cases/pubg

api_cases:
    resource: "@ApiCasesBundle/Controller/"
    type:     annotation
    prefix:   /api/cases

#dota:
#    resource: "@DotaBundle/Controller/"
#    type:     annotation
#    prefix:   /

api_login_check:
    path: /api/login_check

api:
    resource: "@ApiBundle/Controller/"
    type:     rest
    prefix:   /api

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

steam:
    resource: "@SteamBundle/Controller/"
    type:     annotation
    prefix:   /

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /backend

_sonata_admin:
  resource: .
  type: sonata_admin
  prefix: /admin

logout:
    path: /logout
