#dota:
#    resource: "@DotaBundle/Controller/"
#    type:     annotation
#    prefix:   /

api:
    resource: "@ApiBundle/Controller/"
    type:     rest
    prefix:   /api

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

steam:
    resource: "@SteamBundle/Controller/"
    type:     annotation
    prefix:   /

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /backend

_sonata_admin:
  resource: .
  type: sonata_admin
  prefix: /admin

logout:
    path: /logout
