security:
    encoders:
        AppBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        steamauth:
            id: steam.user_provider
        main:
            entity:
                class: AppBundle\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            security: true
            provider: steamauth
            steam:
                default_route: app.skins.main
            remember_me:
                secret: '%secret%'
            form_login:
                provider: main
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /
            anonymous: true

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/api, roles: ROLE_USER }
        - { path: ^/backend, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }