security:
    encoders:
        AppBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_ALLOWED_TO_SWITCH: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_SONATA_ADMIN]

    providers:
        steamauth:
            id: steam.user_provider
        main:
            entity:
                class: AppBundle\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                provider: main
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api:
            pattern:   ^/api/cases
            anonymous: true
            stateless: true
            lexik_jwt: ~

        main:
            pattern: ^/
            security: true
            provider: steamauth
            switch_user: { role: ROLE_ADMIN, parameter: _want_to_be_this_user }
            steam:
                default_route: app.skins.main
            remember_me:
                secret: '%secret%'
            form_login:
                provider: main
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /
            anonymous: true

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/api, roles: ROLE_USER }
        - { path: ^/backend, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }