services:
    steam.user_provider:
        class: AppBundle\Security\SteamUserProvider
        arguments: [ '@doctrine.orm.default_entity_manager', '@app.service.user_service', '%steam.user_class%' ]

    app.service.user_service:
        class: AppBundle\Services\SteamUserService
        arguments: ['@steam.api_profile', '@app.service.upload_image']

    app.repository.product:
        class: AppBundle\Repository\ProductPriceRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\ProductPrice

    app.service.upload_image:
        class: AppBundle\Services\UploadImageService
        public: false
        arguments: ['%steam_community_image_url%']

    app.service.steam_user_inventory:
        class: AppBundle\Services\SteamUserInventoryService
        arguments:
            - '@app.repository.product'
            - '@steam.api_inventory'
            - '@snc_redis.default'
            - '%steam_community_image_url%'

    app.service.add_product_sell:
        class: AppBundle\Services\SaveSellProductService
        arguments: ['@doctrine.orm.entity_manager', '@snc_redis.default', '@app.service.upload_image', '@logger']

    api.service.validator_item_sell:
        class: ApiBundle\Service\ValidatorItemSellService
        arguments: ['@validator']
