services:
    # SteamBundle
    steam.user_provider:
        class: AppBundle\Security\SteamUserProvider
        arguments: [ '@doctrine.orm.default_entity_manager', '@app.service.user_service', '%steam.user_class%' ]

    # AppBundle
    app.service.user_service:
        class: AppBundle\Services\SteamUserService
        arguments: ['@steam.api_steam_profile', '@app.service.upload_image']

    app.form.message_type_form:
        class: AppBundle\Form\MessageTypeForm
        arguments: ['@security.token_storage']
        tags:
            - { name: form.type }

    app.service.upload_image:
        class: AppBundle\Services\UploadImageService
        public: false
        arguments: ['%steam_community_image_url%']

    app.service.steam_user_inventory:
        class: AppBundle\Services\SteamUserInventoryHandler
        arguments:
            - '@app.repository.skins_price'
            - '@steam.api_inventory'
            - '@snc_redis.default'
            - '%steam_community_image_url%'

    app.service.save_sell_skins_handler:
        class: AppBundle\Services\SellSkins\AddSellHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@doctrine.dbal.default_connection'
            - '@snc_redis.default'
            - '@app.service.upload_image'
            - '@logger'

    # Ввод/Вывод денег и оплата товара
    app.service.payment.pay_in_out:
        class: AppBundle\Services\Payment\PayInOutService
        arguments: ['@doctrine.dbal.default_connection', '@app.repository.user', '@logger']

    app.service.payment.payment_skins:
        class: AppBundle\Services\Payment\PaymentSkinsService
        arguments:
            - '@doctrine.dbal.default_connection'
            - '@app.repository.user'
            - '@app.repository.skins_price'
            - '@old_sound_rabbit_mq.trade_product_producer'
            - '@logger'

    # repository service
    app.repository.user:
        class: AppBundle\Repository\UserRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\User

    app.repository.skins_price:
        class: AppBundle\Repository\SkinsPriceRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\SkinsPrice

    # twig function
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }

    # ApiBundle
    api.service.validator_item_sell:
        class: ApiBundle\Service\ValidatorItemSellService
        arguments: ['@validator']

    api.service.news_like:
        class: ApiBundle\Service\NewsLikeService
        arguments: ['@doctrine.orm.entity_manager', '@security.token_storage', '@logger']

    api.service.news_comment:
        class: ApiBundle\Service\NewsCommentService
        arguments: ['@doctrine.dbal.default_connection', '@security.token_storage', '@logger']

    # ProcessingBundle
    processing.is_online.is_online_handler:
        class: ProcessingBundle\OnlineUser\IsOnlineHandler
        arguments: ['@doctrine.dbal.default_connection', '@app.repository.user', '@logger']

    # listener
    app.switch_user_listener:
        class: AppBundle\EventListener\SwitchUserListener
        tags:
            - { name: kernel.event_listener, event: security.switch_user, method: onSwitchUser }