services:
    app.repository.product:
        class: AppBundle\Repository\ProductPriceRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\ProductPrice

    app.service.upload_image:
        class: AppBundle\Services\UploadImageService
        public: false
        arguments: ['%steam_community_image_url%']

    app.service.steam_user_inventory:
        class: AppBundle\Services\SteamUserInventoryService
        arguments:
            - '@app.repository.product'
            - '@steam.api_inventory'
            - '@snc_redis.default'
            - '%steam_community_image_url%'

    app.service.add_product_sell:
        class: AppBundle\Services\SaveSellProductService
        arguments: ['@doctrine.orm.entity_manager', '@snc_redis.default', '@app.service.upload_image', '@logger']
