services:
    steam.security.authentication.provider:
        class: SteamBundle\Security\Authentication\SteamProvider
        arguments: [ '@steam.user_provider', '@guzzle.client.steam' ]
        public: false

    steam.security.authentication.listener:
        class: SteamBundle\Security\Firewall\SteamListener
        arguments: [ 'home', '@security.token_storage', '@security.authentication.manager', '@router' ]
        public: false

    steam.security.authentication.entry_point:
        class: SteamBundle\Security\EntryPoint\SteamEntryPoint
        arguments: [ '@security.http_utils' ]
        public: false

    # api method
    steam.director.steam_api_director:
        class: SteamBundle\Director\SteamApiDirector

    steam.modal.api_method:
        class: SteamBundle\Modal\ApiMethod
        arguments: ['@guzzle.client.steam']

    steam.modal.api_steam_method:
        class: SteamBundle\Modal\ApiSteamMethod
        arguments: ['@guzzle.client.steam']

    steam.abstract_method:
        abstract: true
        public: false
        arguments: ['@steam.modal.api_method', '%steam.steam_api_url%', '%steam.steam_key%', '%locale%']

    steam.dota_method.heroes:
        class: SteamBundle\DotaMethod\HeroesBuilderDotaMethod
        parent: steam.abstract_method

    steam.api_heroes:
        class: SteamBundle\Director\SteamApiDirector
        factory: ['@steam.director.steam_api_director', 'builder']
        arguments: ['@steam.dota_method.heroes']

    steam.dota_method.rarities:
        class: SteamBundle\DotaMethod\RaritiesBuilderDotaMethod
        parent: steam.abstract_method

    steam.api_rarities:
        class: SteamBundle\Director\SteamApiDirector
        factory: ['@steam.director.steam_api_director', 'builder']
        arguments: ['@steam.dota_method.rarities']

    steam.steam_method.profile:
        class: SteamBundle\SteamMethod\ProfileUserMethod
        public: false
        arguments: ['@steam.modal.api_steam_method', '%steam.steam_api_url%', '%steam.steam_key%', '%locale%']

    steam.api_profile:
        class: SteamBundle\Director\SteamApiDirector
        factory: ['@steam.director.steam_api_director', 'builder']
        arguments: ['@steam.steam_method.profile']

    steam.api_inventory:
        class: SteamBundle\DotaMethod\InventoryBuilderDotaMethod
        arguments:
            - '@steam.modal.api_method'
            - '@security.token_storage'
            - '%steam.steam_community_url%'
            - '%steam.steam_inventory_count%'