services:
    api_cases.service.case_open:
        class: ApiCasesBundle\Service\CaseOpenHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@doctrine.dbal.default_connection'
            - '@security.token_storage'
            - '@api_cases.service.games'
            - '@logger'

    api_cases.service.cases_user_sell_skins:
        class: ApiCasesBundle\Service\CasesUserSellSkinsHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@doctrine.dbal.default_connection'
            - '@old_sound_rabbit_mq.live_drop_producer'

    api_cases.service.cases_user_pick_up_skins:
        class: ApiCasesBundle\Service\CasesUserPickUpSkinsHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@doctrine.dbal.default_connection'
            - '@old_sound_rabbit_mq.live_drop_producer'

    api_cases.service.cases_contract:
        class: ApiCasesBundle\Service\CasesContractHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@doctrine.dbal.default_connection'

    api_cases.validator.domain_id:
        class: ApiCasesBundle\Validator\DomainIdValidator
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: validator.constraint_validator, alias: api.validator.domain_id }

    api_cases.service.games:
        class: ApiCasesBundle\Service\GamesService
        arguments:
            - '@snc_redis.default_client'

    api_cases.listener.domain_id:
        class: ApiCasesBundle\Listener\DomainIdListener
        arguments: ['@validator']
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    api_cases.service.payment_handler:
        class: ApiCasesBundle\Service\PaymentHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@doctrine.dbal.default_connection'
            - '@logger'
