fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: '^/', stop: true }

    view:
        default_engine: none
        failed_validation: HTTP_BAD_REQUEST
        view_response_listener: 'force'
        formats:
            rss: false
            xml: false
            json: true
        mime_types:
            json: ['application/json', 'application/json;version=1.0', 'application/json;version=1.1']

    allowed_methods_listener: true
    access_denied_listener:
        json: true
    routing_loader:
        default_format: json