nelmio_api_doc:
    documentation:
        host: cgrays.loc
        schemes: [http, https]
        info:
            title: API PUBG
            description: Api for pubg
            version: 0.0.1
        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Value: Bearer {jwt}'
                name: Authorization
                in: header
        security:
            - Bearer: []
    areas:
        path_patterns:
            - ^/api/cases/pubg(?!/doc$)