knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: order # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: 'AppBundle:Pagination:pagination.html.twig'     # sliding pagination controls template
        sortable: 'AppBundle:Pagination:sortable_link.html.twig' # sort link template