old_sound_rabbit_mq:
    connections:
        default:
            host: '%rabbit_mq_host%'
            port: '%rabbit_mq_port%'
            user: '%rabbit_mq_user%'
            password: '%rabbit_mq_pass%'
            vhost:    '%rabbit_mq_vhost%'
            lazy:     true
            connection_timeout: 60
            read_write_timeout: 60

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: false

            # requires php-amqplib v2.4.1+
            heartbeat: 30

    producers:
        trade_product:
            connection:       default
            exchange_options: {name: 'trade_product', type: fanout}

        parser_price:
            connection:       default
            exchange_options: {name: 'parser_price', type: direct}

        parser_skins:
            connection:       default
            exchange_options: {name: 'parser_skins', type: direct}

        live_drop:
            connection:       default
            exchange_options: {name: 'live_drop', type: fanout}

        metrics_cases:
            connection:       default
            exchange_options: {name: 'metrics_cases', type: fanout}

    consumers:
        is_online_user:
            connection:       default
            queue_options:    {name: 'is_online_user'}
            exchange_options: {name: 'is_online_user', type: direct}
            callback:         processing.online_user.is_online

        parser_price:
            connection:       default
            queue_options:    {name: 'parser_price'}
            exchange_options: {name: 'parser_price', type: direct}
            callback:         processing.parser.price

        parser_skins:
            connection:       default
            queue_options:    {name: 'parser_skins'}
            exchange_options: {name: 'parser_skins', type: direct}
            callback:         processing.parser.skins

        metrics_cases:
            connection:       default
            queue_options:    {name: 'metrics_cases'}
            exchange_options: {name: 'metrics_cases', type: fanout}
            callback:         processing.metrics.cases

services:
    processing.online_user.is_online:
        class: ProcessingBundle\OnlineUser\IsOnlineConsumer
        arguments: ['@doctrine.dbal.default_connection', '@logger']

    processing.parser.price:
        class: ProcessingBundle\Parser\PriceConsumer
        arguments: ['@doctrine.dbal.default_connection', '@logger']

    processing.parser.skins:
        class: ProcessingBundle\Parser\SkinsConsumer
        arguments: ['@processing.parser.skins_handler', '@processing.parser.error_handler', '@logger']

    processing.metrics.cases:
        class: ProcessingBundle\Metrics\CasesConsumer
        arguments: ['@processing.metrics.persister', '@logger']
