old_sound_rabbit_mq:
    connections:
        default:
            host: '%rabbit_mq_host%'
            port: '%rabbit_mq_port%'
            user: '%rabbit_mq_user%'
            password: '%rabbit_mq_pass%'
            vhost:    '%rabbit_mq_vhost%'
            lazy:     true
            connection_timeout: 60
            read_write_timeout: 60

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: false

            # requires php-amqplib v2.4.1+
            heartbeat: 30

    producers:
        trade_product:
            connection:       default
            exchange_options: {name: 'trade_product', type: fanout}

        live_drop:
            connection:       default
            exchange_options: {name: 'live_drop', type: fanout}

        metrics_cases:
            connection:       default
            exchange_options: {name: 'metrics_cases', type: fanout}

        parser_pubg:
            connection:       default
            exchange_options: {name: 'parser_pubg', type: fanout}

    consumers:
        is_online_user:
            connection:       default
            queue_options:    {name: 'is_online_user'}
            exchange_options: {name: 'is_online_user', type: direct}
            callback:         processing.online_user.is_online

        parser_price:
            connection:       default
            queue_options:    {name: 'parser_price'}
            exchange_options: {name: 'parser_skins', type: fanout}
            callback:         processing.parser.price

        parser_skins:
            connection:       default
            queue_options:    {name: 'parser_skins'}
            exchange_options: {name: 'parser_skins', type: fanout}
            callback:         processing.parser.skins

        parser_skins_iamge:
            connection:       default
            queue_options:    {name: 'parser_skins_iamge'}
            exchange_options: {name: 'parser_skins', type: fanout}
            callback:         processing.parser.skins

        parser_pubg_price:
            connection:       default
            queue_options:    {name: 'parser_pubg_price'}
            exchange_options: {name: 'parser_pubg', type: fanout}
            callback:         processing.parser_pubg.price

        parser_pubg_skins:
            connection:       default
            queue_options:    {name: 'parser_pubg_skins'}
            exchange_options: {name: 'parser_pubg', type: fanout}
            callback:         processing.parser_pubg.skins

        metrics_cases:
            connection:       default
            queue_options:    {name: 'metrics_cases'}
            exchange_options: {name: 'metrics_cases', type: fanout}
            callback:         processing.metrics.cases

services:
    processing.online_user.is_online:
        class: ProcessingBundle\OnlineUser\IsOnlineConsumer
        arguments: ['@doctrine.dbal.default_connection', '@logger']

    processing.parser.price:
        class: ProcessingBundle\ParserCSGO\PriceConsumer
        arguments: ['@processing.parser.price_handler', '@logger']

    processing.parser.skins:
        class: ProcessingBundle\ParserCSGO\SkinsConsumer
        arguments:
            - '@doctrine.dbal.default_connection'
            - '@processing.parser.skins_handler'
            - '@logger'

    processing.parser.skins_image:
        class: ProcessingBundle\ParserCSGO\SkinsImageConsumer
        arguments: ['@processing.parser.skins_image_handler', '@logger']

    processing.parser_pubg.price:
        class: ProcessingBundle\ParserPUBG\PriceConsumer
        arguments:
            - '@doctrine.dbal.default_connection'
            - '@doctrine.orm.entity_manager'
            - '@logger'

    processing.parser_pubg.skins:
        class: ProcessingBundle\ParserPUBG\SkinsConsumer
        arguments:
            - '@doctrine.dbal.default_connection'
            - '@processing.parser_pubg.skins_handler'
            - '@logger'

    processing.metrics.cases:
        class: ProcessingBundle\Metrics\CasesConsumer
        arguments: ['@processing.metrics.persister', '@logger']
