sonata_admin:
    # for hide mosaic view button on all screen using `false`
    show_mosaic_button:   true

sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]

